package com.metalist.bookreader.utils

val constPages = listOf(
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/1.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/2.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/3.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/4.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/5.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/6.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/7.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/8.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/9.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/10.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/11.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/12.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/13.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/14.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/15.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/16.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/17.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/18.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/19.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/20.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/21.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/22.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/23.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/24.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/25.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/26.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/27.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/28.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/29.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/30.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/31.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/32.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/33.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/34.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/35.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/36.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/37.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/38.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/39.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/40.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/41.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/42.jpg",
    "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/attackofthetitans/glava2/43.jpg"
)

val constPdf = "https://dvty-vinn-dev-app-0.organism.aibody.io/manga/za-dvoma-zaytsiamy/glava1/za-dvoma-zaytsiamy.pdf"